import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Database } from "@/integrations/supabase/types";
import { format } from "date-fns";

// Define strict type for rows coming from DB
type Manifest = Database['public']['Tables']['carrier_manifests']['Row'];

export const generateManifestPDF = (manifest: Manifest) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // Helper for aligned text
    const rightText = (text: string, y: number) => {
        doc.text(text, pageWidth - 14, y, { align: "right" });
    };

    // 1. Header & Title
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185);
    doc.text("CARRIER MANIFEST", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Generated by RouteWise System", 14, 25);

    // Meta Info
    doc.setTextColor(0);
    doc.setFontSize(10);
    doc.text(`Manifest #: ${manifest.manifest_number}`, 14, 35);
    doc.text(`Type: ${manifest.manifest_type || 'N/A'}`, 14, 40);

    rightText(`Status: ${manifest.status}`, 35);
    rightText(`Date: ${new Date().toLocaleDateString()}`, 40);

    // 2. Route & Logistics Section
    autoTable(doc, {
        startY: 45,
        head: [['Logistics & Route Information']],
        body: [
            [`Origin: ${manifest.origin_hub}`],
            [`Destination: ${manifest.destination_hub}`],
            [`Dispatch Time: ${manifest.dispatch_date_time ? format(new Date(manifest.dispatch_date_time), 'PPpp') : '-'}`],
            [`Carrier: ${manifest.carrier_name} (${manifest.carrier_phone || '-'})`],
        ],
        theme: 'striped',
        headStyles: { fillColor: [44, 62, 80], fontSize: 11 },
        styles: { fontSize: 10, cellPadding: 2 }
    });

    // 3. Vehicle & Driver
    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 5,
        head: [['Vehicle & Driver Details', '']],
        body: [
            ['Registration No', manifest.vehicle_reg_no],
            ['Driver Name', manifest.driver_name],
            ['CNIC', manifest.driver_cnic || '-'],
            ['Mobile', manifest.driver_mobile || '-'],
            ['Make / Model', `${manifest.vehicle_make || ''} ${manifest.vehicle_model || ''}`],
            ['Fitness / Ins.', `Fit: ${manifest.fitness_cert_no || '-'} / Ins: ${manifest.vehicle_insurance_company || '-'}`],
        ],
        theme: 'grid',
        headStyles: { fillColor: [44, 62, 80] },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } }
    });

    // 4. Customs & Cargo
    if (manifest.gd_number || manifest.container_no) {
        autoTable(doc, {
            startY: (doc as any).lastAutoTable.finalY + 5,
            head: [['Customs & Cargo Specification', '']],
            body: [
                ['GD Number', manifest.gd_number || '-'],
                ['Container No', manifest.container_no || '-'],
                ['Seal No', manifest.seal_no || '-'],
                ['Agent / Clearing', manifest.clearing_agent_name || '-'],
                ['Commodity', manifest.commodity_description || '-'],
                ['Gross Weight', `${manifest.gross_weight || 0} kg`],
            ],
            theme: 'grid',
            headStyles: { fillColor: [192, 57, 43] }, // Red for customs
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } }
        });
    }

    // 5. Operations & Security
    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 5,
        head: [['Operational & Security Checks', '']],
        body: [
            ['Trip ID', manifest.trip_id || '-'],
            ['Security Status', manifest.security_check_status || 'PENDING'],
            ['Guard Name', manifest.security_guard_name || '-'],
            ['Police Escort', manifest.police_escort_required ? 'REQUIRED' : 'NO'],
            ['Gate / Shift', `${manifest.departure_gate || '-'} / ${manifest.dispatch_shift || '-'}`]
        ],
        theme: 'grid',
        headStyles: { fillColor: [39, 174, 96] }, // Green for ops
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } }
    });

    // 6. Signatures
    const finalY = (doc as any).lastAutoTable.finalY + 30;

    // Ensure we don't go off page
    if (finalY > 250) {
        doc.addPage();
        doc.text("Signatures", 14, 20);
    }

    doc.setFontSize(10);
    doc.text("_______________________", 14, finalY);
    doc.text("Dispatch Officer", 14, finalY + 5);

    doc.text("_______________________", 80, finalY);
    doc.text("Carrier / Driver", 80, finalY + 5);

    doc.text("_______________________", 150, finalY);
    doc.text("Security In-Charge", 150, finalY + 5);

    // Footer
    const totalPages = doc.internal.pages.length - 1; // jsPDF array has empty first element sometimes
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, 290, { align: 'center' });
    }

    doc.save(`Manifest_${manifest.manifest_number}.pdf`);
};
